language: python
python:
  - "3.6"
install:
  - pip install coverage==3.7.1 codecov
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - codecov -t eeba8193-7a1a-404a-bb47-e18c26283696
